### ISSUE TITLE
Improve instructions

### ISSUE THREAD

**Issue by boardtc** [shanoor/kubectl-aliases-powershell#3]
1. I tried to directly download the kubectl_aliases.ps1 file but it saves as a HTML file, I found what you have to do is click on the raw button and then when the tab opens right click and select save as
2. To know where you profile directory is to save it to type $PROFILE in your PowerShell
3. You need to add the kubectl function to your profile file *$PROFILE* for the aliases to work, say this rather than the confusing "To print the full command before running it, "

**Comment by shanoor** [comment]
1. It's fixed, I updated the README to the raw file directly
2. Maybe I should add something about this in the README
3. The README already contains a command that updates your profile file
