### ISSUE TITLE
User help please

### ISSUE THREAD

**Issue by boardtc** [shanoor/kubectl-aliases-powershell#4]
When I try kubectl command parameters with K they are not recognised, what am I doing wrong?

e.g.:  
```
PS> k get namespace
> kubectl get namespace
Error: unknown command "get namespace" for "kubectl"
```

**Comment by cprivitere** [comment]
Just tried this on my machine and it does not happen.

**Comment by chringel21** [comment]
Try replacing `kubcetl` with `kubectl.exe` in the ps1-file. Worked for me.
