### ISSUE TITLE
Provide some clarification for getting ready on windows 10

### ISSUE THREAD

**Issue by Z-Farook** [shanoor/kubectl-aliases-powershell#5]
![image](https://user-images.githubusercontent.com/46790696/109284190-dfdc2d00-781f-11eb-8b41-7ed67161b7d9.png)

![image](https://user-images.githubusercontent.com/46790696/109284704-6f81db80-7820-11eb-9358-76e11a8ea3ff.png)

**Comment by shanoor** [comment]
README has been updated, it should be easier to get it working
